### ISSUE TITLE
Error in Angular2PrestaModule.forRoot(ap2) in Ionic Framework

### ISSUE THREAD

**Issue by JoCarrasco** [SKaDiZZ/angular2-presta#4]
![image](https://user-images.githubusercontent.com/34868263/43864889-f3e422a6-9b2e-11e8-84b6-b3528d516082.png)
![image](https://user-images.githubusercontent.com/34868263/43864943-1ae54ca4-9b2f-11e8-98dd-be2bbed375bd.png)
![image](https://user-images.githubusercontent.com/34868263/43864977-316fa316-9b2f-11e8-8d5d-7ef852484085.png)

**Comment by cristhian-net** [comment]
Same here. I need a patch asap. How may I contribute to fix this? Any clues please.

![image](https://user-images.githubusercontent.com/12214429/43901240-5ed82fce-9bbd-11e8-951e-29ee9994bfa9.png)

**Comment by cristhian-net** [comment]
I've found some peer dependencies in package.json. So when installing all packages from npm I can see 
`npm WARN angular2-presta@0.1.17 requires a peer of @angular/common@^6.0.0-rc.0 || ^6.0.0 but none is installed. You must install peer dependencies
yourself.
npm WARN angular2-presta@0.1.17 requires a peer of @angular/core@^6.0.0-rc.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.`.
I think that Angular5 (or backwards) is not compatible anymore because of this. Could you confirm @SKaDiZZ ? Maybe not requiring the new http module and http client will work for all versions and not just Angular 6+. I'm new at this kind of code inspections, so I cannot confirm that this is the problem.
I don't want to upgrade my Angular version, so I think I will fork this repo and rollback to another commit.

cc @JoCarrasco 

Thanks for this library @SKaDiZZ !

**Comment by SKaDiZZ** [comment]
I can confirm that there isn't this issue with angular 6 project. But I get same error with Ionic. That could be the issue @CristhianUNSa with dependencies. This library has been generated using latest angular-cli library generator and it automatically added those peer dependencies. Also this version of library is upgraded to work with latest angular version and as you may know RXjs imports are changed. and need to be updated to work with angular 6.

**Comment by JoCarrasco** [comment]
Surely. Can we help to fix this?

**Comment by SKaDiZZ** [comment]
I guess solution would be releasing library with support for older angular versions and changing back imports in angular2-presta.service.ts to support older rxjs version. Because eventually ionic will be upgraded to use angular 6 so this would be way not to break it in the future.

**Comment by SKaDiZZ** [comment]
I will try to release that and I will notify you guys

**Comment by cristhian-net** [comment]
Thanks @SKaDiZZ.

**Comment by SKaDiZZ** [comment]
@JoCarrasco @CristhianUNSa 
There is solution!  Install older version of library so you should try:
```bash
npm install angular2-presta@0.1.14 --save
```

**Comment by cristhian-net** [comment]
Perfect. My app is now calling the webservice

**Comment by SKaDiZZ** [comment]
You can check documentation for that version on npm 
https://www.npmjs.com/package/angular2-presta/v/0.1.14
I will update documentation to point to this solution for users using versions of angular prior to angular 6

**Comment by JoCarrasco** [comment]
Thanks
